### ISSUE TITLE
Build File Modified Message Needs To Be Improved

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1026]
From @JustinProminic 

----------------------

While using Moonshine -- the same Development version I just e-mailed you about yesterday, so I'm not re-sending the About Dialog version contents with this e-mail -- I received this message:

![image](https://user-images.githubusercontent.com/24370870/166205870-55f35c2f-2c8b-4a5f-8aad-ecf7b304f110.png)

while editing only this line:
`<version>0.2.1-SNAPSHOT</version>`
of this file: _pom.xml_

The above message needs to be improved significantly.

It does not tell the user what is about to happen with explicit details.

It needs to tell the user exactly what will happen if they choose Now.   Also, I don't love the idea of having a "never" or "always" option for this, because that would imply the system is going to make changes without the user knowing.

Please add this to the issue list for a future release.

-----------------------

**Comment by rat-moonshine** [comment]
Initially, I was thinking of https://github.com/Moonshine-IDE/Moonshine-IDE/issues/633 of which the alert is. But, later I realised the implementation from #633 is suppose to show a more simpler dialog:

![image](https://user-images.githubusercontent.com/24370870/166228219-68c0539d-00e8-446c-b0f6-f9c87807aea1.png)

I tried to do a search for the string in related projects (Moonshine, moonshine-feathersui-text-editor, MoonshineGUICore, moonshine-openfl-language-client) but I didn't found a reference there. I was wondering where this was coming from.

@piotrzarzycki21 @joshtynjala do you have any knowledge about this alert (?)

**Comment by piotrzarzycki21** [comment]
> Initially, I was thinking of #633 of which the alert is. But, later I realised the implementation shows a more simpler dialog:
> 
> ![image](https://user-images.githubusercontent.com/24370870/166228219-68c0539d-00e8-446c-b0f6-f9c87807aea1.png)
> 
> I tried to do a search for the string in related projects (Moonshine, moonshine-feathersui-text-editor, MoonshineGUICore, moonshine-openfl-language-client) but I didn't found a reference there. I was wondering where this was coming from.
> 
> @piotrzarzycki21 @joshtynjala do you have any knowledge about the alert mentioned in the original issue (?)

That string is in [UpdateTabCommand](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/e95b5e587ce1e75d77eaddb8833201df61865c9b/ide/MoonshineSharedCore/src/actionScripts/controllers/UpdateTabCommand.as#L95)

**Comment by rat-moonshine** [comment]
> That string is in [UpdateTabCommand](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/e95b5e587ce1e75d77eaddb8833201df61865c9b/ide/MoonshineSharedCore/src/actionScripts/controllers/UpdateTabCommand.as#L95)

No, I meant about the alert from the original issue.

**Comment by joshtynjala** [comment]
> A build file was modified. Do you want to synchronize the Java classpath/configuration?

This message comes from the Java language server. It is not from our code in Moonshine.

As I recall, this message appears when you modify pom.xml or build.gradle. It's basically asking if the Eclipse project files (which are managed by the language server) should be updated or not. In VSCode, where users like to tinker with config files and things, it makes more sense to give the user a choice. In Moonshine, where we do a lot more things automatically, I think that we should default to the behavior that is triggered when "always" is chosen. Of course we want to update the project files because otherwise the code intelligence will be left state where the provided information may be out of date.

I will need to research exactly how to do that, but I think it will be relatively simple. Probably just passing a configuration setting to the language server.

**Comment by joshtynjala** [comment]
> A build file was modified. Do you want to synchronize the Java classpath/configuration?

Moonshine-IDE/Moonshine-IDE@295d8eb08f118ca23cb19aa444242d003458a1c8 and Moonshine-IDE/moonshine-openfl-language-client@4a6e5ea25ac007079dbe694c9207692d1393dd73 should together prevent this confusing message from appearing.
