### ISSUE TITLE
Merge Haxe Conversion Branch

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1102]
Now that 3.3.3 is released, we would like to merge the Haxe Conversion (#1035) from @Igazine :  https://github.com/Moonshine-IDE/Moonshine-IDE/tree/features/haxeconversion

This can be tested with the Bamboo builds:
https://static.moonshine-ide.com/downloads/releases/dev/macos/branches/features/haxeconversion/
https://static.moonshine-ide.com/downloads/releases/dev/windows/branches/features/haxeconversion

**Comment by Aszusz** [comment]
Hi @Igazine 
Please, refresh your branch with the latest master. If you encounter particularly hard conflicts, please let us know.

**Comment by Igazine** [comment]
@Aszusz is this because of the licence changes? While I see the pull request and the separate branch, I don't see the actual changes in master (I see and merge other changes related to other parts development)

https://github.com/Moonshine-IDE/Moonshine-IDE/pull/1092

**Comment by Aszusz** [comment]
No, it's not because of the license. The license branch isn't merged to master, and I wouldn't like it to be yet. Your changes come first.

I'm asking you to refresh with the master branch because:
- the latest haxe conversion builds failed
- at least one of the errors is because of a mismatch between moonshine-ide and sdk-installer
- bamboo told me no agents are able to build this job, possibly because of outdated dependencies
- there were a lot of changes due to the release and I believe integrating them into your code before tests is generally a good idea

So, I'm hoping after merging the master the builds will succeed, and even if not I'll have an easier time comparing them to the current version to fix things.

**Comment by Igazine** [comment]
Like I mentioned a couple of times earlier, I'm doing **daily master merges** into my branch, otherwise it would be really difficult to keep up with the changes.

I'm trying to figure out why the Bamboo Windows build fails, while the same commit [builds perfectly fine on GitHub](https://github.com/Moonshine-IDE/Moonshine-IDE/actions/runs/3190473839). In the meantime I pushed the changes to [SDK Installer](https://github.com/Moonshine-IDE/Moonshine-SDK-Installer/tree/features/haxeconversion) (please note the different branch)

In the meantime I'm having difficulties building the app on Windows (related to VisualEditorConverterLib, and only on Windows), so once I cleaned that up, I'll push the rest of the commits.

**Comment by JoelProminic** [comment]
Sorry, the Bamboo Windows remote agent was broken.  I just restarted it, and that should resolve the problem.  I see the macOS build is fixed already.

**Comment by Igazine** [comment]
Thank you, @JoelProminic 

According to our conversation today with the help of @piotrzarzycki21 , @rat-moonshine , and @Aszusz , the Windows build errors have been cleaned up, so please expect another update today in features/haxeconversion branch which should trigger new builds on GitHub and Bamboo

**Comment by Aszusz** [comment]
Hi @Igazine
Pete and I have tested both Win and Mac builds and we didn't find any critical issues.
Please, merge your branch to master at your earliest convenience.

**Comment by piotrzarzycki21** [comment]
@Igazine Where we are with this merge ?

**Comment by Igazine** [comment]
features/haxeconversion branch has been merged into master (changes have been pushed to the repo). i wanted to make sure everything is flawless

please pull the latest changes.
thank you

**Comment by piotrzarzycki21** [comment]
After opening in Moonshine IDE MoonshineGUICore and have following error:

```
: Installing dependency lime...
: You already have lime version 8.0.0 installed
: Installing dependency openfl...
: You already have openfl version 9.2.0 installed
: Installing dependency actuate...
: You already have actuate version 1.8.9 installed
: Installing dependency feathersui...
: You already have feathersui version 1.0.0 installed
: Installing dependency amfio...
: You already have amfio version 1.0.1 installed
: Installing dependency format...
: You already have format version 3.5.0 installed
: Installing dependency markdown-openfl-textfield...
: You already have markdown-openfl-textfield version 1.0.2 installed
: Installing dependency moonshine-openfl-language-client...
: Error: Failed with error: No such Project : moonshine-openfl-language-client
: Failed to install dependency: moonshine-openfl-language-client
```

I did install things using command from MoonshineGUICore README. Did I miss something ?

**Comment by Igazine** [comment]
The [Ant buildfile](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/build/build-lib.xml#L969) should take care of all the haxelib installation

https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git – this is the GitHub repo in question, not sure why the installation fails

could you please try this in terminal / command line to see if it succeeds?

`haxelib git moonshine-openfl-language-client https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git`

**Comment by piotrzarzycki21** [comment]
I did that: 
```
haxelib git moonshine-openfl-language-client https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git
You already have moonshine-openfl-language-client version git installed.
Updating moonshine-openfl-language-client version git ...
moonshine-openfl-language-client was updated
Library moonshine-openfl-language-client current version is now git
Installing dependency openfl 9.2.0
You already have openfl version 9.2.0 installed
```

I understand that Ant can do things, but I'm not interested into building things trough Ant in the first place. That part of the project I need to have ability to code in Moonshine. Could you please open in installed version of Moonshine that part of the project and check if it's failing ?

**Comment by Igazine** [comment]
I have the same error building the project in Moonshine. I'll take a quick look, give me some time, please.

**Comment by Igazine** [comment]
If I revert back the changes (until I figure this error out, along with a few others), will the version bump automatically up, so people can update the development version, or the version number should be changed manually?
Thank you

**Comment by Igazine** [comment]
The reason of this error is because every haxelib dependency is being installed by a script at startup / project open, and it uses the standard haxelib installation command line. However there are specific haxelibs dependencies for the GUICore that are not available on HaxeLib project yet as standard libraries, and need to be manually installed from GitHub.

I'm not sure how to mark these libraries in Moonshine config/scripts in order to use a different command line for these specific libraries. We need to come up with a more general solution that works in every possible Haxe project

E.g. the current config is trying to execute this:

`haxelib install moonshine-openfl-language-client`

while the moonshine-openfl-language-client is currently only available on GitHub, so it should be installed like this:

`haxelib git moonshine-openfl-language-client https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git`

but the script does not know that, and it fails.

**Comment by rat-moonshine** [comment]
> If I revert back the changes (until I figure this error out, along with a few others), will the version bump automatically up, so people can update the development version, or the version number should be changed manually?

Usually every commit triggers the build process at Bamboo. I'm not sure if _revert_ triggers that. The last build number I see #1254. I can run this manually if you requires.

**Comment by rat-moonshine** [comment]
Okay. I started the builds manually for both macOS and Windows target.

**Comment by Aszusz** [comment]
@rat-moonshine 
Too soon. @Igazine hasn't pushed his revert yet.

@Igazine 
```
$: /c/MoonshineSDKs/Haxe/haxe-4.2.4/haxelib.exe git moonshine-openfl-language-client https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git

C:/MoonshineSDKs/Haxe/haxe-4.2.4/haxelib.exe: error while loading shared libraries: api-ms-win-crt-locale-l1-1-0.dll: cannot open shared object file: No such file or directory
```
There may be a problem with our default haxlib installation on Windows

**Comment by rat-moonshine** [comment]
> Too soon. @Igazine hasn't pushed his revert yet.

Ah! I misread the comment. Okay, let me know if we still needs a manual build.

**Comment by Igazine** [comment]
Could someone please make the revert? Now my entire local repo is messed up, all the deleted files came back, it'll take some time until I clean this up.
Thank you

**Comment by piotrzarzycki21** [comment]
Why revert anything ? Fix things up on master - no hurry with that. I can wait. Please do not revert. Fix this using issue for merge and we will be good.

**Comment by piotrzarzycki21** [comment]
> The reason of this error is because every haxelib dependency is being installed by a script at startup / project open, and it uses the standard haxelib installation command line. However there are specific haxelibs dependencies for the GUICore that are not available on HaxeLib project yet as standard libraries, and need to be manually installed from GitHub.
> 
> I'm not sure how to mark these libraries in Moonshine config/scripts in order to use a different command line for these specific libraries. We need to come up with a more general solution that works in every possible Haxe project
> 
> E.g. the current config is trying to execute this:
> 
> `haxelib install moonshine-openfl-language-client`
> 
> while the moonshine-openfl-language-client is currently only available on GitHub, so it should be installed like this:
> 
> `haxelib git moonshine-openfl-language-client https://github.com/Moonshine-IDE/moonshine-openfl-language-client.git`
> 
> but the script does not know that, and it fails.

Moved this one to separate issue to discuss more problems. I will shed more of my thoughts about that there. I'm closing Merge issue cause it was successful. All remaining issues should be raised separately and fixed on master if possible.
