### ISSUE TITLE
AS3ProjectPlugin canCreateProject() should be refactored

### ISSUE THREAD

**Issue by joshtynjala** [Moonshine-IDE/Moonshine-IDE#1164]
The `canCreateProject()` method in `AS3ProjectPlugin` is implemented with name comparisons using `== -1` (meaning that it wants to ensure that the project name _doesn't_ contain the specified string):

```as3
// AS3ProjectPlugin
private function canCreateProject(event:NewProjectEvent):Boolean
{
	var projectTemplateName:String = event.templateDir.fileBridge.name;
	return projectTemplateName.indexOf(ProjectTemplateType.VISUAL_EDITOR) == -1 &&
		projectTemplateName.indexOf(ProjectTemplateType.JAVA) == -1 &&
		projectTemplateName.indexOf(ProjectTemplateType.GRAILS) == -1 &&
		projectTemplateName.indexOf(ProjectTemplateType.HAXE) == -1 && 
		projectTemplateName.indexOf(ProjectTemplateType.ONDISK) == -1 &&
		projectTemplateName.indexOf(ProjectTemplateType.GENERIC) == -1;
}
```

Other projects plugins implement `canCreateProject()` with` != -1` (meaning the opposite).

```as3
// HaxeProjectPlugin
private function canCreateProject(event:NewProjectEvent):Boolean
{
    var projectTemplateName:String = event.templateDir.fileBridge.name;
    return projectTemplateName.indexOf(ProjectTemplateType.HAXE) != -1;
}
```

`AS3ProjectPlugin.canCreateProject()` should switch to `!=`. The reason for this is simple: When adding a new language, you shouldn't need to modify `AS3ProjectPlugin` to exclude your new language. At Justin's request, I'm writing a guide/tutorial for adding a new language, and this is a step that seems unnecessary and confusing.

I was hoping that I could do it quickly on my own, like this:

```as3
// AS3ProjectPlugin (proposed)
private function canCreateProject(event:NewProjectEvent):Boolean
{
    var projectTemplateName:String = event.templateDir.fileBridge.name;
    return projectTemplateName.indexOf(ProjectTemplateType.ACTIONSCRIPT) != -1 ||
	    projectTemplateName.indexOf(ProjectTemplateType.AWAY3D) != -1 ||
	    projectTemplateName.indexOf(ProjectTemplateType.FEATHERS_SDK) != -1 ||
	    projectTemplateName.indexOf(ProjectTemplateType.FLEX) != -1 ||
	    projectTemplateName.indexOf(ProjectTemplateType.ROYALE) != -1;
}
```

However, it appears that `ProjectTemplateType` has several constants each for Flex and Royale, and I suspect that not all of them are regular AS3 projects (though, I could be wrong). I'd prefer not to break anything here. Especially for project types that might not be tested frequently, so I'm requesting that someone more familiar with all of the project types (such as @rat-moonshine) should probably make the appropriate change, whatever it may be. I assume that my proposal above is nearly correct, and it's just a couple of special cases for Flex/Royale.

**Comment by rat-moonshine** [comment]
Following are the templates which manage by `AS3ProjectPlugin`. Other templates has their own plugin classes to manage. Based on the _types_ it seems mainly ActionScript and Royale templates are managed by the `AS3ProjectPlugin`.

Template Title | Type | Notes
--------------|-------------| ----------
ActionScript Project | ActionScript |
Away3D Project | ActionScript |
Feathers SDK Desktop Project | ActionScript |
Feathers SDK Mobile Project | ActionScript |
Flex Browser Project | ActionScript |
Flex Desktop Project | ActionScript |
Flex Mobile Project | ActionScript |
Library Project (Flex) | ActionScript |
Apache Royale Project REST | Royale | During project creation it was throwing NPE because of `$project.projectName` unavailability. I fixed this, @piotrzarzycki21 please give this some tests if not broke something unintentionally
Royale Browser Project | Royale | 

Based on the above table/types I have updated `AS3ProjectPlugin.canCreateProject(..)` that pass the above types to execute by the plugin class. 

It could have been better if we separate the plugin classes as types like Haxe, Java, OnDisk etc. has. But I assume that would a length of refactoring, and I'm not going into this unless we wants this strongly. 

I don't seen any breaks in my initial tests following the changes.

**Comment by rat-moonshine** [comment]
Thanks for reporting @piotrzarzycki21 . I shall check that shortly.

**Comment by rat-moonshine** [comment]
@piotrzarzycki21 I have re-adjusted the name generation [problem](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1164#issuecomment-1352918389). Please give a test with newer build when you have a chance.

**Comment by rat-moonshine** [comment]
@joshtynjala let me know if the minimal [updates](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1164#issuecomment-1352641000) is sufficient for you to progress. Or, we can/should improve this in any other way.

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 I have re-adjusted the name generation [problem](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/1164#issuecomment-1352918389). Please give a test with newer build when you have a chance.

Thanks I just tested it and everything working fine now.

**Comment by joshtynjala** [comment]
@rat-moonshine Looks good to me. Thank you!
