### ISSUE TITLE
.hxproj Not In The File-Association List For Moonshine

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#1172]
`.hxproj` is the Haxe project configuration file. Double-clicking the file in Finder/Explorer do not opens the project in Moonshine-IDE. This needs to be included in Moonshine's file-association list.

**Comment by JoelProminic** [comment]
Testing on macOS, I found that the .hxproj file opened in a Moonshine editor tab rather than opening the project.

**Comment by rat-moonshine** [comment]
Sorry, I overlooked the need of separate project-file handling ways in file-association plugin. This should be fixed now. Please, check.

**Comment by JoelProminic** [comment]
This is working well on macOS.    I have not tested on Windows yet.

**Comment by JoelProminic** [comment]
I tested this on Windows through macOS Parallels, and it looks like .hxproj is not registered with Moonshine:
![image](https://user-images.githubusercontent.com/24532731/210672648-5972d7fe-5932-4b89-a5e9-cd3a0cde6cd3.png)

For comparison, .javaproj looks like this:
![image](https://user-images.githubusercontent.com/24532731/210672676-616aeed9-7eee-410c-b43d-27c97aa6de6b.png)

Since Parallels has special behavior, this may not have been the best test.  @JesseProminic, please run a quick test if you have a chance.

**Comment by rat-moonshine** [comment]
While testing with Windows build 1354 I also witnessed the problem. It turned out that we're including file-association information in NSIS script for Windows platform, which I missed.

I have included the missing `hxproj` and `genericproj` file-types in the build script. We need to test with >1354 build.

**Comment by JesseProminic** [comment]
I tested a .hxproj in Windows 10 and it opened on Moonshine without any problem.
<img width="884" alt="Screenshot 2023-01-06 at 9 39 51 AM" src="https://user-images.githubusercontent.com/96078188/211045714-e3caf9ec-4a01-45a5-9c1d-6b9ad453f98b.png">

**Comment by JoelProminic** [comment]
@rat-moonshine tested the .genericproj case, so this issue is resolved.
