### ISSUE TITLE
Add Path Context for Recent Files

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1231]
While testing #1230, we also noticed "duplicate" entries for common file names:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/3a0f7643-e580-421f-82dc-5a8ca9055964)
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/b07ac614-b1e5-4e6c-b278-eb4aafc65b95)

These are probably separate files, but since we can't tell which project they are associated with, it is not practical to open a specific file from Recents.   So, we would like to add some context to help clarify this.  Some options:
- Show the project name in parenthesis.  I think this would be the most useful solution, but it is also the most complicated to implement.  If no project is detected for the file, we can display "Unknown" for the project, or hide the extra information in this case.
- Show the full path, using "..." to shorten it to fit.  I think the end of the path is generally the most useful part here.
- Show the full path in a tooltip.  This would probably be the simplest solution, as long as tooltips are available in the menu.

**Comment by rat-moonshine** [comment]
Some thoughts on the options suggested:

1. This indeed an expensive process to determine if a file is part of project, specially if the file resides deep inside the folders; Furthermore, showing project name for some files and "Unknown" for non-project files - I feel this all a little confusing 
2. I vote for this
3. I don't think we can show tooltip in menu items - specially, on macOS

While working on 2, I was thinking how the "..." format we wants to present. Few options crossed my mind as follows:
- `.../MyProjectName/src/MyProjectFile.as`
- `/Users/$user/.../MyProjectName/src/MyProjectFile.as`
- `MyProjectFile.as (.../MyProjectName/src)`

We needs to shorten the label as much as possible since horizontal-space is limited here, and some file/folder name could be larger. So I chose first option from here, and I'd like to know  how this feels to you.

**(NOTE: Many things are still needs to be tuned - this update only displays the new label format in home screen)**

Currently, I'm showing last 3 values if separated by file-separator, i.e. 
`.../MyProjectName/src/MyProjectFile.as`

On screen this looks something like this:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24370870/ba5b47e1-c701-4391-ad33-8a1580cc227c)

If we feel the format meets the purpose, I shall continue with other tuning.

**Comment by rat-moonshine** [comment]
Updates:

- Mixed text style in recent-files list (italic, normal)
- Opening new file properly renders with newer style format
- Fixed recent-files menu item disable problem (was occurring after opening a file from recent-list)

This is now ready for full release.

**Comment by JoelProminic** [comment]
The Recents section looks like this now:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/07a2a3d2-0b62-4d30-9c64-bd02b48d1415)

I would like to see the file names stand out even more (with bold or underline), but @rat-moonshine was concerned that this would look jarringly out of place.

I also see the menu is updated.  This has no contrast for now between the path and file names:
![image](https://github.com/Moonshine-IDE/Moonshine-IDE/assets/24532731/eb890a5b-567c-4991-b914-c67a90acb41f)

Also note that in my examples, the limited nesting on the path means that Java files with packages don't show the project names.  Even a class with a single-level package is nested 4 levels deep in the project.  That said, showing more of the path would use too much space.  Also, the class files are less likely to have duplicate names than configuration-by-convention file names like build.gradle or pom.xml.

In general, I think this is a useful improvement.  We can discuss tomorrow if we want any further changes before closing the issue.

**Comment by JoelProminic** [comment]
I think this is good enough for now.  We can revisit this when we work on converting the Home page.
