### ISSUE TITLE
Add a Generic Template

### ISSUE THREAD

**Issue by oninoshiko** [Moonshine-IDE/Moonshine-IDE#700]
When pulling down a fresh git repository, moonshine wants to create a new project, which is fine. the problem is it is rather adamant about selecting a template. Not all projects will fit nicely under the list of specialized templates.

We need a generic template for projects that do not fit into one of the existing categories.

UPDATE:  Branch references, for convenience:
- Branch:  features/issue_700_generic_template
- Builds:  https://moonshine-ide.com/downloads/releases/dev/macos/branches/features/issue_700_generic_template

**Comment by rat-moonshine** [comment]
Currently, Moonshine supports the opening of known project types. An arbitrary project open may not does anything other than displaying as a generic folder. The type of opening may create other complexities to the present logic where Moonshine expects a known-project. This needs investigation.

**Comment by rat-moonshine** [comment]
From an earlier discussion with @JoelProminic on this, he expected following behaviour from the implementation:

> For #700, I think we had discussed pushing this to a later release. But the idea is that we need to open a project with no required source directory, but it should support Ant, Maven, and Gradle build scripts. The build scripts would also be optional. 
>  
> We already should have support for Ant. For Gradle and Maven, we need to detect build.gradle or pom.xml, repectively, and enable a corresponding "Build" action in the Project menu.
>  
> The build action should work similar to the Run Grails Command action that we implemented in https://github.com/Moonshine-IDE/Moonshine-IDE/issues/570

While working on the implementation a few other things crossed my mind too:

1. I assume as we needs an option to open an arbitrary directory into sidebar (#700) we also wants an option to create a non-project directory that starts into sidebar (#990)
2. Since Moonshine not suppose to necessarily supply or place any template files during this type of project creation or import, my idea is to open/list by the directory content that points during its creation. This will create/open by the directory that pointed to during such type of project creation (#990) - the directory could be non/empty 
3. Since we wants to support Ant, Maven, and Gradle - do we wants any settings to be saved for such generic type of project/directory opening? I assume if we wants any settings save we might then need to introduce a configuration file. If we wants to determine the ability to Ant, Maven or Gradle at run-time, then we shall not need this

**Comment by rat-moonshine** [comment]
Some initial updates are ready for a test:

- Creation of generic project
- Open/import of directory as a generic project
- Basic file creation to the opening project

A build can be tested using macOS branch build plan from Bamboo.

**Comment by rat-moonshine** [comment]
I have added `build.gradle` and `pom.xml` file detection on folder root and generation of `Run Gradle Command` and `Build with Apache Maven` under Project menu, respectively. 

However, to support #570 like functionality where user choose to change Gradle/Maven command by going into project's settings and save - if we want this to be session specific then we should be good. If we wants to save the changes for later use upon project re-opening, then we'll need to have the settings saved into respective project's configuration.

I was not keen to manage a separate configuration file for generic project, and populate the file into opening folder's directory. But if we wants to have the Gradle/Maven settings to be saved for non-session use, then we'll need to introduce a new configuration file for such project type.

**Comment by JoelProminic** [comment]
I tried the branch build (build 163), and I don't see the generic template in the New Project list.  I checked both the menu and the home screen.  I was expecting a name like "Generic Project", but I am not seeing this.
![image](https://user-images.githubusercontent.com/24532731/165989810-4993c9b0-eff1-4f4d-ba69-78a5d1e07051.png)

I tried importing a project instead.  I used [this project](https://github.com/Moonshine-IDE/Vagrant-REST-Interface) as an example.
1. Manually clone the repository to a temporary directory
2. Project > Open/Import Project, and browse to the cloned repository
3. Choose "Open as generic project"
4. Moonshine showed the import screen below.  BUG:  the form showed the Parent Directory, rather than the location of the project to import.  The Parent Directory did not match the original location
5. I tried creating the project with the default selection, to see if it would copy the repository.   BUG:  instead, it created a blank `Vagrant REST-Interface` directory under the Parent Directory
6. BUG:  the opened project was blank, since it showed the new location
![image](https://user-images.githubusercontent.com/24532731/165989849-91f514c3-caec-47fa-8630-1f38ff40e19e.png)

I see two ways we can do this:
1. Enforce the selected path to the originally selected directory, and prevent changes. This should not update the Parent Directory list.
2. Let the user choose a different directory, and copy the project into this directory.  I don't think this is the use case that most users will want, and it adds extra complication to the process.  This will make even less sense when it triggers after a Git > Manage Repositories > Checkout.

**Comment by JoelProminic** [comment]
I did another test with the repository in my temp_workspace directory, so that it would match Parent Directory.  This opened properly, but I didn't see any project files added.  This means that I have to import the project as a generic project each time I open it.  I was expecting to see a file like `%project%.genproj` added to the project directory, so that it could be reopened with Moonshine later.

**Comment by rat-moonshine** [comment]
>  I checked both the menu and the home screen. I was expecting a name like "Generic Project", but I am not seeing this.

I confirm this. An option is suppose to be there in home-screen and I can have the option in my local tests, I'll check what prevents it from appearing in package build.

From the test-steps of `Vagrant-REST-Interface` directory, I'm trying to document and explain against original test-steps:

1. Manually clone the repository to a temporary directory
2. Project > Open/Import Project, and browse to the cloned repository
3. Choose "Open as generic project"
4. Moonshine showed the import screen below. The "Parent Directory" populated as it was expected and set the project-name by the browsed/target directory name. This design to support the ways existing project-creation/import dialog works. I'm not clear with the bug @JoelProminic reported in original step.4
![image](https://user-images.githubusercontent.com/24370870/166206948-9de8c155-5b18-494c-a81c-72de03d50022.png)
5. I tried creating the project with the default selection, the directory opens with its files into sidebar. I see @JoelProminic have mentioned creation of a blank `Vagrant REST-Interface` directory under the Parent Directory - is it possible that by mistake you've modified the project name (?) If that is then I'm sure you shall open by a blank/new directory. We probably need to work on that and prevent any naming changes in the open-project window.
![image](https://user-images.githubusercontent.com/24370870/166207385-419eac45-4f4e-4ec7-9c3f-ad3ffa140c37.png)

I think I was previously thinking on this option, too:

> 3. Do not show the import form for the generic template, and use the default name.

This will save us from any over-doing from option 1 or 2. But I wanted to discuss if we want to go with option.3 after you give some tests to the build. Until the native `File` supports any naming convention we should be good to open the directory as it is without needing the import dialog in-between. 

I shall work on removal of import dialog which is a bit irritating too in frequent use.

**Comment by rat-moonshine** [comment]
>  I checked both the menu and the home screen. I was expecting a name like "Generic Project", but I am not seeing this.

I confirm this. An option is suppose to be there in home-screen and I can have the option in my local tests, I'll check what prevents it from appearing in package build.

From the test-steps of `Vagrant-REST-Interface` directory, I'm trying to document and explain against original test-steps:

1. Manually clone the repository to a temporary directory
2. Project > Open/Import Project, and browse to the cloned repository
3. Choose "Open as generic project"
4. Moonshine showed the import screen below. The "Parent Directory" populated as it was expected and set the project-name by the browsed/target directory name. This design to support the ways existing project-creation/import dialog works. I'm not clear with the bug @JoelProminic reported in original step.4
![image](https://user-images.githubusercontent.com/24370870/166207883-ce08ca93-ba2b-49f2-9d36-106fe85e4b55.png)
5. I tried creating the project with the default selection, the directory opens with its files into sidebar. I see @JoelProminic have mentioned creation of a blank `Vagrant REST-Interface` directory under the Parent Directory - is it possible that by mistake you've modified the project name (?) If that is then I'm sure you shall open by a blank/new directory. We probably need to work on that and prevent any naming changes in the open-project window.
![image](https://user-images.githubusercontent.com/24370870/166207385-419eac45-4f4e-4ec7-9c3f-ad3ffa140c37.png)

I think I was previously thinking on this option, too:

> 3. Do not show the import form for the generic template, and use the default name.

This will save us from any over-doing from option 1 or 2. But I wanted to discuss if we want to go with option.3 after you give some tests to the build. Until the native `File` supports any naming convention we should be good to open the directory as it is without needing the import dialog in-between. 

I shall work on removal of import dialog which is a bit irritating too in frequent use.

**Comment by rat-moonshine** [comment]
> This means that I have to import the project as a generic project each time I open it. I was expecting to see a file like %project%.genproj added to the project directory, so that it could be reopened with Moonshine later.

This is something I was looking for a guidance in my [comment](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/700#issuecomment-1113398680) earlier.

Since I didn't wanted to put an alien file to an arbitrary directory, I didn't chose the way at first place.

However, you can still able to open the once opened generic project from recent-opened-list when the folder doesn't has a configuration file.

Once we implement option.3 from https://github.com/Moonshine-IDE/Moonshine-IDE/issues/700#issuecomment-1113529041 we don't need to go through import-dialog each time.

**Comment by rat-moonshine** [comment]
- Ensure a new option for Generic Project appears in home screen
- Removes import project dialog during opening of a generic project - this cuts the opening time of a directory into sidebar

**Comment by rat-moonshine** [comment]
I have updated the generic project management with an introduction of `.genericproj` file as discussed. Following are a list of new updates for the type of import/creation:

- Population of `.genericproj` configuration file in case of newly created and imported project/directory
- Enable hyphen insertion during project naming in new project creation dialog
- Opening from rencently-opened list now reads from `.genericproj`
- Other adjustment includes Maven and Gradle settings save to `.genericproj`
- File association for `.genericproj`

Following is a chart of tests taken.

\- | Previous configuration file | Opens to sidebar | New configuration file | Created as new directory | Opens with existing directory
------|------------|------------|-----------|----------|----------------
**Open/Import Project** | No | Yes | Created. Yes | No | Yes
**New Generic Project** - No existing directory location | No | Yes | Created. Yes | Yes | No
**New Generic Project** - Pointed to existing directory location | No | Yes | Created. Yes | No | Yes
**New Generic Project** - Pointed to existing directory location | Yes | No. New project creation dialog shows error `Project can not be created to an existing project directory` | NA | NA | NA
**Opens from recently-opened list** | Yes | Yes | NA | No | Yes

Gradle and Maven settings also tested saving to the project's configuration file. However, during a freshly detected Gradle, Maven availability, the build settings remain blank for them.

**Comment by JoelProminic** [comment]
I see the current content of the .genericproj file looks like this:

```
<project>
  <classpaths>
    <class path="/Users/-snip-/Documents/temp/Vagrant-REST-Interface"/>
  </classpaths>
</project>
```

I want to avoid using absolute paths in these project files .  This becomes a problem when sharing projects with other developers ([Example](https://github.com/Moonshine-IDE/Moonshine-IDE/commit/f0656b492a78465199c88d1b6c08205c8bb78e32)).  I don't want to refactor this for other projects right now, but I don't want to add new problems.

I found the "New Generic Project - Pointed to existing directory location" case confusing.  I clarified with @rat-moonshine that this triggered when the Parent Directory + Project Name matches an existing directory.  However, I think this case should be treated as a name conflict instead - this is the behavior I am used to seeing for other project types.   Project types like Flex Desktop do support importing a project from the new project form, but you have to check the "Project with existing source" option.  I think it is better to keep it simple and use File > New for projects that don't exist yet, and Open/Import Project to setup projects that haven't been configured in Moonshine yet.

**Comment by rat-moonshine** [comment]
Updates:

- New project creation restrictions are now match to other project creation ways
- We probably do not need to generate `classpaths` in its configuration file. I removed its population

**Comment by JoelProminic** [comment]
I did some more testing.  I checked some other actions that use the open/import logic.

Action | Config File | Result
-------|-------------|-------
Project > New > Generic Project | N/A | Works
Project > New > Generic Project, directory exists | N/A | Shows error (see below)
File > Open/Import Project | Yes | Works
File > Open/Import Project | No | 
File > Open/Import Project, multiple subprojects | No generic projects | Works normally, does not prompt for generic project creation.
File > Open/Import Project, multiple subprojects | At least one generic project | Generic project is detected and opened properly
File > Import Project Archive | No | "No valid Moonshine project found to the archive. Please check." (Is this consistent with the behavior for other project types?)
File > Import Project Archive | Yes | FAILED:  "No valid Moonshine project found to the archive. Please check."
Recents | Yes | Works
Workspace Switch | Yes | Yes
Open on Restart | Yes | FAILED:  Generic projects are not reopened
Git > Clone | No | Prompts to import, generic import works
Git > Clone | Yes | Opens without prompt
SVN > Checkout | Yes | Prompts to import, generic import works
SVN > Checkout | No | Opens without prompt
Open .genericproj from Finder (macOS) | FAILED:  Opens as file rather than opening project
Open .genericproj from Finder (Windows) | TODO


Change the error for an existin project directory to this in both the in-line error and the the popup.:

> Project directory already exists:
> %full_path%

For the error prompt, the "Project creation terminated" message should be on a separate line:

> Project directory already exists:
> %full_path%
> Project creation terminated.


Also, I see that Moonshine is adding a blank README.md for imported files.   I think this is good for the new project template, but it doesn't make sense to add it for new projects.

@JesseProminic, it would be appreciated if you help test @rat-moonshine's updates tomorrow.  I have download links for this branch in the description.

**Comment by rat-moonshine** [comment]
I have updated the change messages from https://github.com/Moonshine-IDE/Moonshine-IDE/issues/700#issuecomment-1119066543 into project creation dialog for generic project, as well.

**Comment by rat-moonshine** [comment]
This issue is now merged into `master`.

**Comment by rat-moonshine** [comment]
> Some Windows tests would be good, but otherwise this is ready for a merge:

I give some tests on Windows, and they worked [accordingly](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/700#issuecomment-1121272777).

**Comment by JoelProminic** [comment]
@rat-moonshine reminded me that Gradle and Maven integration had been added.  This worked mostly like I expected.  

Build Script | Detected | Command Works | Commands saved | Notes
-------------|----------|---------------|----------------|------
Ant | No (Expected?) | Yes, from both context and Other menus | N/A | 
Gradle | Yes | Yes | Yes | 
Maven | Yes | Yes | Yes | 

For Ant, I didn't see a Ant section in the project configuration, and Project > Build with Apache Ant was missing.  Is this something that is hard coded for projects like Flex?

I also checked the configuration files, and I see that an absolute path was stored for Maven.  This is consistent with other Maven projects, though, so we'll revisit this later.:

```
<project>
  <mavenBuild>
    <option mavenBuildPath="/Users/-user-/Documents/Flex/temp_workspace/TestGenericMaven_0510"/>
```

**Comment by rat-moonshine** [comment]
Ant build file detection and handling now added to generic projects. Following paths based on standard Ant file detections in Moonshine:
- `$projectFolder/build.xml`
- `$projectFolder/build/$anyFile.xml`

**Comment by JoelProminic** [comment]
I did some tests by removing the .as3proj file from a Flex Desktop project.

Ant script | Project > Build with Apache Ant  | Project Settings
-----------|----------------------------------|-----------------
build/build.xml | Present, Works | None
build/other.xml (renamed) | Missing | None
build/build-other.xml (renamed) | Missing | None
build.xml (added) | Present, Works | None

Did you expect to have a project settings page for Ant?  I do see some Ant settings for a Flex Desktop project.
![image](https://user-images.githubusercontent.com/24532731/169341836-58fb316e-9520-4d68-8a61-bdc1eef79401.png)

I saw that the `build/*.xml` pattern didn't detect files besides build.xml.  How generic do we want ot make this?  I know we have cases like `build-lib.xml`.

**Comment by piotrzarzycki21** [comment]
@rat-moonshine please check Windows build - it may be failing after some changes.

**Comment by rat-moonshine** [comment]
This problem should be fixed now. 

Note, Moonshine tries to determine an Ant `.xml` by reading its content which starts with `<project>` tag. In case of a blank `build/build.xml` Moonshine fails to determine it's a valid Ant file thus it may not add Ant build option under `Projects` menu. In case of `build.gradle` there was no such content test regulation I see, thus a blank `build.gradle` also avail the build command for Gradle under `Projects` menu.

**Comment by JoelProminic** [comment]
I tested Generic project with a blank build.gradle, pom.xml, and build/build.xml.  It detected the first two, and ignored build.xml, as expected.  Maven and Gradle fail to run, of course, but I saw the same errors when I tried builds in Terminal.

Similarly if I have a blank build.xml file in the project root, it is treated as an Ant project (and fails in an expected way).  This behavior makes sense, since this is the "standard" location and name for an Ant build script.

I also did a test with a valid Ant script at `build/build.xml` and this worked properly.
