### ISSUE TITLE
Default Checkout Directory Set To Moonshine Workspace

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#920]
From @JustinProminic 

> We need to default Parent directory to the workspace default instead of making the user type it in or select it here:
> 
> ![image](https://user-images.githubusercontent.com/24370870/141761180-77f61ebc-3751-470f-86ad-e7c813984e54.png)
> 
> it should just auto-populate with the value from here:
> 
> ![image](https://user-images.githubusercontent.com/24370870/141761333-d80d661c-92d6-401d-ad96-ea01a1e37b53.png)
>

**Comment by rat-moonshine** [comment]
I updated the target-folder generation in following manner:

Nature | Behaviour in Clone/Checkout window
----------| --------------------
Fresh install, no project ever created | Parent directory will be "" unless user already browsed any location using file-browser
Previously project created | Parent directory will be populate with current default `Parent Directory` from project-creation dialog
User browsed any location using file-browser | Parent directory will populate by last browsed location using the file-browser

**Comment by JoelProminic** [comment]
I was able to confirm the last two cases with the latest build, but I don't think the logic should work as you defined:

Case | Behaviour in Clone/Checkout window | Reasoning
-----| -----------------------------------|----------
Fresh install, no project ever created | Use the same default directory as New Project | This may not be a desirable location, but it is a working default that won't require any additional access for new users
Project previously created | Use the last selected project directory | This assumes that the user will want to checkout/clone the project in the same directory where they created other projects.  Choosing a new directory here should also update the last Project Directory (and history available in New Project)
User browsed any location using file-browser | Use the above logic instead | The last browsed directory is not necesarily a project directory.  It could be an SDK directory instead. 

For example, here is a test after I set the SVN path.  This path is undesirable (and would fail, since it treats the svn binary as a directory).

![image](https://user-images.githubusercontent.com/24532731/142516763-124e5106-8018-451d-afb2-bec4ebab64a5.png)

I have been thinking about other updates for the project directory logic.  These features are outside of the scope of this issue, but I wanted to share some early ideas:
- remove the current workspaces setting
- Add a settings page to list the project directories
- Add directories to this list manually if user wants to set this up in advance
- Remove directories that are no longer desired
- Fix how the import directories are handled for this

**Comment by rat-moonshine** [comment]
Based on the above observation I have adjusted path-population for clone/checkout window in following way:

No. | Case | Behaviour in Clone/Checkout window | Reasoning
---|-----| -----------------------------------|----------
1 | Fresh install, no project ever created | Use the same default directory as New Project | -
2 | Cloned/checkout a project to any particular location | Use the same location from last checkout/clone. This is session specific and avail throughout a session only | Usually in a concurrent checkout/clone situation users generally likes to have the path auto-populates with the last checkout directory. It could be annoying if user requires to change the directory every time from `No.3` location to earlier checkout location
3 | Project previously created | Use the last selected project directory unless `No.2` data is available | -

Please, check.

**Comment by JoelProminic** [comment]
I moved the discussion for a more advanced interface to #941.

The new cases sound fine for me.  I'm not sure if we should make a distinction between cases 2 and 3, but we can wait to change this as part of #941.

I'd like to wait to test case 1 until I can test #917 and #919 at the same time.  Resetting the application settings will also be needed to properly test the other cases, but there is some testing I can do in the meantime.

**Comment by JoelProminic** [comment]
I ran through some tests without clearing settings.  The logic works well, but I confirmed that the last Clone location is not preserved after a restart.  
1. Restart Moonshine
2. Open Git > Manage Repositories
3. Select a repository and click Clone.  The parent directory is populated to a previously used location
4. Choose a different location and Clone
5. Open a Clone prompt.  The parent directory matches the new location.
6. Open a Checkout prompt.  The parent directory matches the new location.
7. Create a new project:  File > New > Flex Desktop Project. The Parent Directory was not updated to match the directory used for the clone.  This is consistent with the current logic
8. Choose a directory different than the last clone directory and click Create
9. Open a Clone prompt.  The parent directory matches the last Clone location.
10. Open a Checkout prompt.  The parent directory matches the last Clone location.
11. Restart Moonshine
12. Open a Clone prompt.  This shows the directory for the last New project instead
13. Open a Checkout prompt.  This shows the directory for the last New project instead

The disadvantage to this strategy is that if the user never creates a fresh project, the project directory will keep resetting back to the Moonshine default, which could be as annoying as leaving it blank.

I think it would be better to have Clone/Checkout update the Project Directories list, but this starts getting into the features I proposed in #941.

We should do some test with a fresh environment later.

**Comment by rat-moonshine** [comment]
> The logic works well, but I confirmed that the last Clone location is not preserved after a restart

Do we used to preserve the last cloned/checkout directory on restart (?) 

Currently, the `No.2` stated as session-specific and the last cloned directory remain available throughout the session, so I believe the above test-behaviours are as expected. 

If we want to preserve the last-checkout/cloned path even after a restart, then with current logic clone/checkout prompt will always open by the last known checkout/cloned path, by overriding last created project's path since last cloned/checkout path is available.

**Comment by JoelProminic** [comment]
I don't really want to separately save the last clone/checkout path. I can see some value to this, but I think keeping it separate from the Project Directory list will just cause confusion in the long term.  I'd like for it to update the Project Directories list, but we can save this to be part of #941.

This is waiting for a fresh environment test, but otherwise it seems to be working as expected for now.

**Comment by JoelProminic** [comment]
Testing with a fresh non-Sandbox build, I see that the default New Project and Checkout directory is `/Users/%user%/Documents`.   This matches the logic described above,, but I thought that the default was a directory in `~/Containers`.  Am I confusing this with the App Store build?

**Comment by rat-moonshine** [comment]
Yes, a sandbox build (App Store build) always stores its data under `/Library/Containers` when a non-sandbox at `/Library/Application Support`. 

The first default-opening location for a project creation is always `File.documentsDirectory` - however when the API between sandbox and non-sandbox, it supplies a different path in Moonshine. When in non-desktop the path provides as expected (`/Users/$user/Documents`), it returns a strange path in sandbox (`/Users/$user/Library/Containers/...`). 

I confirm if I installs a sandbox build, the opening project creation path remains into `/Containers/...` path:

![image](https://user-images.githubusercontent.com/24370870/146499656-4e8ee8ae-cd3e-47b3-98c1-359aa00dcbad.png)

**Comment by JoelProminic** [comment]
Thanks for the clarification.  This issue should be good, then.
