### ISSUE TITLE
Saving SVN Credential Do Not Working

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#928]
@JustinProminic reported this,

> I'm constantly getting re-prompted for SNV credentials.
> 
> The "save until Moonshine exits" seems to do nothing, or not work.
> 
> ![image](https://user-images.githubusercontent.com/24370870/142814806-a8cb15cc-dbd6-49aa-945f-9268097f081a.png)

This probably while using the Development build v3.3.0.

**Comment by JoelProminic** [comment]
Some other interfaces that may need this format:
- SVN/Git Authentication errors
- Duplicates in Git > New Branch
- Duplicates in File > Workspace > Create Workspace - I see this uses a different format (Also, this should be "Workspace already exists.":

![image](https://user-images.githubusercontent.com/24532731/172660913-1b647971-a9bb-459c-8c72-51b0b8dffc23.png)


I expect that there are other cases I am forgetting here, but hopefully this will give us ideas for finding similar cases.

**Comment by rat-moonshine** [comment]
This problem should be fixed now. Following are test-results:

- Create a SVN entry under `Subversion > Repository Browser` that needs an authentication
- Upon checkout provide authentication details while selecting `Save until Moonshine exits` checkbox
- SVN repository checkout completes and Moonshine stores the authentication details in memory (repository specific)
- Re-checkout the same SVN repository item - this time Moonshine do not prompts for password and checkout the repository using the in-memory stored auth details to the repository
- Restart Moonshine, try to checkout the same SVN repository again
- Moonshine asks with password prompt

**Comment by JoelProminic** [comment]
I did some tests today, and I found that the updated didn't work when the "Need Authentication" option is not selected in the repository configuration.  
1. Delete the saved SVN Password from the keychain
2. Checkout a project
3. Enter the password and choose to save it in Moonshine
4. Delete the password from the keychain again.   This is added automatically for me - I'm not sure why this does not happen for @JustinProminic
5. Checkout the project again.  BUG:  I am prompted to enter my password again

I see that if I choose the "Need Authentication" option, I am required to enter the username.  Since @JustinProminic's screenshot shows no username, I suspect that he has the same configuration as me.

On a side note, I can't edit an existing repository entry to change "Need Authentication" - I get a prompt for a duplicate entry.   I'll create a separate issue for this.

Also "Need Authentication" should be "Needs Authentication".  This doesn't matter too much, but it seems a bit awkward in the current state.  Maybe we need to phrase it differently to avoid this awkwardness instead - I'll update the issue if I have an idea for this.

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/174723134-7bb3dfdd-c863-44c6-aa52-85bf554cbcca.png)

**Comment by rat-moonshine** [comment]
![image](https://user-images.githubusercontent.com/24370870/174723247-1100cf08-10b3-4ae4-a538-b361bdf2b3d6.png)

**Comment by JoelProminic** [comment]
This works as expected for Checkout

Needs Authentication | Save Password | Result
---------------------|---------------|-------
False | False | Prompts for password
False | True | Authenticates
True | False | Prompts for password
True | True | Authenticated

However, I saw problems on other actions once I had the password saved.

Action | Result
-------|-------
Commit | BUG:  Prompts for password
Update | BUG:  Prompts for password
Browse in Manage Repositories | Works


I see the checkbox still shows "Need Authentication".

**Comment by rat-moonshine** [comment]
Commit and Updates now tested using saved credential in application lifecycle. Please, check.
