### ISSUE TITLE
File System Watcher

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#948]
I just committed my file system watcher implementation. It checks for changes every 5 seconds, and the project tree will update automatically. Additionally, it notifies the language servers of these changes too.

When a project is added, Moonshine automatically listens for any changes to its files, including all nested subdirectories. It stops listening when a project is closed (or when Moonshine exits). It currently ignores _.git_ and _.svn_ folders.

The following new events are dispatched on the global event dispatcher when a change is detected: `WatchedFileChangeEvent.FILE_CREATED`, `WatchedFileChangeEvent.FILE_DELETED`, and `WatchedFileChangeEvent.FILE_MODIFIED`. Any plugin may listen for these events, if needed. As I said, I already added listeners for the language server managers, and to the ProjectPlugin to update the file tree.

Please let me know if you encounter any issues, so that I can fix them. Thanks!

_Originally posted by @joshtynjala in https://github.com/Moonshine-IDE/Moonshine-IDE/issues/911#issuecomment-975808121_

This is a big update, so I am moving it to a separate issue.

**Comment by JoelProminic** [comment]
I noticed this behavior today on macOS Catalina, non-Sandbox:
1. Open a Java Gradle project
2. Expand `src/main/java`
3. Right-click on `java` and click New > Folder
4. Create the new folder
5. BUG:  after 5-10 seconds, the entire `src/` tree collapses, and I need to expand it again manually.

Unfortunately, this does not trigger consistently for me.  I noticed it multiple times when I was creating a nested package (net/prominic/test), but I couldn't reproduce it after closing and reopening the project.

**Comment by joshtynjala** [comment]
> BUG: after 5-10 seconds, the entire src/ tree collapses, and I need to expand it again manually.

My latest commit should improve this situation a bit. It may still collapse some sub-directories in the file tree, but not the root quite as often.

My change was to make sure that it refreshes the deepest directory possible. Previously, if an exact directory match could not be found, it refreshed the root of the project, and that's why it collapsed everything. Now, it will collapse much less. Ideally, I think that it should keep all child directories open that were previously open before the refresh. I don't know the internals of this tree component to know how easy that would be. I've never worked on this part of the code.

Additionally, I should warn you that I'm not completely sure about the purpose of the FileWrapper class in Moonshine. This part of the code seems to deal with FileWrapper a lot. I understand that FileLocation exists as an abstraction to represent files on both desktop and web, and that's why we don't use AIR's File class directly. I've concluded that FileWrapper seems to a higher level abstraction over FileLocation, but I don't know what it adds that FileLocation doesn't already do on its own.

With my lack of understanding here, It's possible that my "improvement" to `UtilsCore.findFileWrapperAgainstFileLocation()` will break something unexpectedly. Since this method never returns null, and it always defaults to the root directory when no match is found, I assumed that a closer match would be safe to return instead. Can someone review this change from a code perspective? Since some directories still collapse, I suspect that my solution may not be enough. Maybe someone more familiar with the TreeView.mxml/CustomTree.as components in Moonshine can come up with something better.

**Comment by JoelProminic** [comment]
I think @rat-moonshine is the most familiar with the FileWrapper and tree components for Moonshine.

I'll watch for problems with this while I am doing other tests in Moonshine.

**Comment by rat-moonshine** [comment]
> I understand that FileLocation exists as an abstraction to represent files on both desktop and web, and that's why we don't use AIR's File class directly. I've concluded that FileWrapper seems to a higher level abstraction over FileLocation, but I don't know what it adds that FileLocation doesn't already do on its own.

As you may have noticed that `FileWrapper` was suppose to does many process by its own which are not available in `FileLocation` abstract class, like parsing a directory and populates its children [automatically](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/valueObjects/FileWrapper.as#L204), providing some other informations etc. Having the parsing and auto-populate method was ideal to keep here when you provide a root node to the wrapper, and it'll start populating all its sub-directories and their children in a recursive manner. This is how the sidebar tree was used to populate before we worked on [slow startup problem](https://github.com/Moonshine-IDE/Moonshine-IDE/issues/756) due to sidebar parsing. 

As you mentioned about `UtilsCore.findFileWrapperAgainstFileLocation()` - it also now make me think that does it still effective after https://github.com/Moonshine-IDE/Moonshine-IDE/issues/756 changes? Previously, it was suppose to work correct since all he directory/children information are already available in the sidebar.

Hypothetically, this still suppose to work because with the `FileLocation` you query this method, possibly the location/directory of the `FileLocation` object already parsed and available to the tree. But, what if some class holds a `FileLocation` and the tree refreshed, directory collapsed and sets their children _null_ - will that `FileLocation` instance be available in tree data-provider at all? That thing needs to be investigated.

**Comment by JoelProminic** [comment]
I noticed that the ordering of files in a project changes when I add a file outside of Moonshine:
1. Create/Open a project
2. Right-click > Copy Path
3. Open a Terminal and `cd` to the path
4. Create a new file with `touch test.txt`
5. Wait for Moonshine to update. BUG:  the files are reordered on the update, and it is no longer alphabetical
6. Refresh the project.  The files are ordered correctly.
![image](https://user-images.githubusercontent.com/24532731/145471027-d89aed33-6ab5-4023-bbb4-356158e60515.png)

This is not a critical bug, but it will be a distraction when it triggers.  We have had other problems with sorting on macOS before (see #650).

**Comment by JoelProminic** [comment]
I moved the ordering issue to #955, so that we can close this issue for the 3.3.0 release.

**Comment by rat-moonshine** [comment]
@joshtynjala how do you compile https://github.com/Moonshine-IDE/Moonshine-IDE/tree/master/ide/FileSystemWatcherWorker. 

I am having trouble running `openfl build flash` to the directory as it reported unknown type `File`. I don't see any `extern` in the directory, I was wondering how you setup this in IDE to access requisite `File` properties.

**Comment by joshtynjala** [comment]
I think you need to use `openfl build air` instead. You should need only the _.swf_ file, and you can ignore any other files that the build produces.
