### ISSUE TITLE
Debugging with custom url stopped working

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Moonshine-IDE#950]
I have in my hosts on url mapped: 

127.0.0.1       dev.prominic.net

I would like to use that as a custom url and debug my application. I think it used to work, but now whether I choose Firefox or Chrome debugger in settings of the project it's failing.

When I do Build & Debug I'm getting following stack trace in Console:

- **Chrome**

```
: Opening to URL: https://dev.prominic.net/prominic/bin/js-debug/index.html
: Launching application using adapter: chrome
: crbug/1173575, non-JS module files deprecated.
```

- **Firefox**

```
: Project Build Successfully.
: Opening to URL: https://dev.prominic.net/prominic/bin/js-debug/index.html
: Launching application using adapter: firefox
: Process error: (node:11853) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
: (Use `node --trace-deprecation ...` to show where the warning was created)
```

Moonshine Development: **3.3.0 Build 2253**
Mac OSX: **Monterey 12.0.1**

**Comment by joshtynjala** [comment]
Does it do anything else, besides displaying text in the console? Does it open a browser window?

**Comment by piotrzarzycki21** [comment]
> Does it do anything else, besides displaying text in the console? Does it open a browser window?

Yes it does open browser window in both cases, but I don't have anything displayed there.

**Comment by joshtynjala** [comment]
Does it display anything if you launch a project that doesn't use a custom host?

**Comment by piotrzarzycki21** [comment]
> Does it display anything if you launch a project that doesn't use a custom host?

Yes without custom host debugging is working at least in Chrome. I didn't check in Firefox.

**Comment by joshtynjala** [comment]
@piotrzarzycki21 Unfortunately, I am unable to reproduce this issue. I started a local HTTP server with my bin/js-debug directory as the document root, and I specified a custom URL to launch in my Royale project Run settings. The custom URL correctly mapped from a domain specified in /etc/hosts to 127.0.0.1 in both Chrome and Firefox.

Did you start a local HTTP server? When you use a custom URL in the project Run settings, Moonshine won't start its own server.

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 Unfortunately, I am unable to reproduce this issue. I started a local HTTP server with my bin/js-debug directory as the document root, and I specified a custom URL to launch in my Royale project Run settings. The custom URL correctly mapped from a domain specified in /etc/hosts to 127.0.0.1 in both Chrome and Firefox.
> 
> Did you start a local HTTP server? When you use a custom URL in the project Run settings, Moonshine won't start its own server.

So the scenario is:
1) I'm starting my https server 
2) Setup custom url in settings
3) I'm choosing from Moonshine "Build & Debug" ?

**Comment by joshtynjala** [comment]
Yes, that's what I did. I used a HTTP server instead of HTTPS to test. It's possible that HTTPS URLs may have issues, depending on certificate validity and all that. It might be worth comparing HTTP and HTTPS on your machine, to see if they both fail, or if it's only HTTPS.

**Comment by joshtynjala** [comment]
If Build & Run does not start a server when there is no custom URL, that seems like a bug to me. Build & Debug and Build & Run should be consistent. Both should start a server when there's no custom URL, and both should not start a server when there is a custom URL.

**Comment by piotrzarzycki21** [comment]
> and both should not start a server when there is a custom URL.

Why they should not start that ?

**Comment by joshtynjala** [comment]
Moonshine should not start a server when there's a custom URL because the user is _probably_ running their own server. Or at least, that was the assumption in the Flex/Flash days. I believe that this option was originally copied to Moonshine from Flash Builder's debug/run options. In Flash Builder, no server was ever started automatically for Flex/Flash apps. With that in mind, the only purpose of allowing a custom URL to be specified was to give users the option to run their Flex/Flash app on their own server (which could be either local or remote) instead of from the local file system. Our Flex apps work the same way, and when we added support for Royale, it inherited that legacy.

To be clear, there's nothing stopping us from adding an option that lets the user choose if they still want Moonshine to start a server when a custom URL is specified. If you want that feature, go ahead and add it. Just make sure that's there's still a way for a user to use their own custom server instead of the one that Moonshine launches automatically. There will still be developers who don't want Moonshine's internal server.

**Comment by piotrzarzycki21** [comment]
Thanks Josh for explanation. I will raise separated issue.
