### ISSUE TITLE
Creating New Form Builder DXL File Throws Exception When Accessed From File Menu

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#982]
When try creating a new "Form Builder DXL File" from `File > New > Form Builder DXL File` it throws following exception:

```
: Error #1009
: TypeError: Error #1009
: 	at actionScripts.plugin.templating::TemplatingPlugin/openOnDiskFormBuilderTypeChoose()
: 	at actionScripts.plugin.templating::TemplatingPlugin/handleNewTemplateFile()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
: 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
: 	at actionScripts.ui.menu::MenuPlugin/redispatch()
```

However the file creation works when using from context-menu in project-tree.

**Comment by rat-moonshine** [comment]
Location | Type | Working
-----------|---------|----------
`File > New` | Form Builder DXL File | Yes
`File > New` | Visual Editor DXL File | Yes
`{context-menu} > New` | Form Builder DXL File | Yes
`{context-menu} > New` | Visual Editor DXL File | Yes

**Comment by JoelProminic** [comment]
These cases work for me as well with the latest nightly build on macOS.   

I tried selecting the project root instead of the appropriate src directory, and I got an error in the UI requiring me to change the path to be under src before I could continue.  This is the expected behavior, and the file creation did not trigger the above error.
