### ISSUE TITLE
Custom Name Show in Activity Monitor Against Running Language Servers Java Instances

### ISSUE THREAD

**Issue by rat-moonshine** [Moonshine-IDE/Moonshine-IDE#992]
From @JustinProminic 

> Please investigate whether you can modify the Java process name that shows up in Activity Monitor to better reflect what it is doing.
> 
> https://stackoverflow.com/questions/4217947/setting-process-name-on-mac-os-x-at-runtime
> 
> Here is an example Moonshine screen shot that is only loading Moonshine itself to edit it.
> 
> The %CPU calmed down by the time I took this screen shot -- after the 9 different Java processes consumed most resources on my computer for a couple of minutes.
> 
> ![image](https://user-images.githubusercontent.com/24370870/158113973-4a83db52-0e87-4eb3-972d-45744bb2a2c8.png)
> 
> It would be wonderful to at least see what they are for in the Process Name column.
> 
> Something like:
> 
> java language server for project: MoonshineWorker

**Comment by joshtynjala** [comment]
In Adobe AIR, this will require a custom native extension.

**Comment by JoelProminic** [comment]
@JustinProminic suggested [this link](https://stackoverflow.com/questions/1057247/how-can-i-set-the-process-name-for-a-java-program) for setting the process name from Java.

The `-Dname=myApp` solution involves adding a dummy argument to the beginning of the process line.  This doesn't help, since Activity monitor does not print any arguments.


The [procname](https://github.com/airlift/procname) solution, sounded promising, but this requires a Linux-only library.

    % make
    cc -Wall -Werror -fPIC -shared -o libprocname.so procname.c
    procname.c:1:10: fatal error: 'sys/prctl.h' file not found
    #include <sys/prctl.h>
             ^~~~~~~~~~~~~
    1 error generated.
    make: *** [all] Error 1


[Apache Procrun](https://commons.apache.org/proper/commons-daemon/procrun.html) is an option for windows, but this wraps the process in a Windows service, which is probably overkill for what we need.

If we don't have any ideas for an easy solution on this, we can close this issue in favor of an interface in Moonshine (#994).

**Comment by rat-moonshine** [comment]
Additionally, I think this is the [StackOvreflow](https://stackoverflow.com/questions/4217947/setting-process-name-on-mac-os-x-at-runtime) link that me and @JoelProminic discussed on some time back.

`lsappinfo setinfo <PID> --name <NAME>`

While the above command looks promising, during my tests I've found this requires `sudo` to correctly execute. Furthermore, it requires PID which is unavailable to us with `NativeProcess`.
